server:
  error:
    include-exception: false
  servlet:
    context-path: /v1/api

logging:
  level:
    com.arthurtira.sdd: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

# AWS Configuration
aws:
  region: eu-west-1




