package com.arthurtira.sdd.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@DynamoDBTable(tableName = "Book")
@AllArgsConstructor
@NoArgsConstructor
public class Book {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "book_id")
    private String bookId;

    @DynamoDBAttribute(attributeName = "book_title")
    private String bookTitle;

    @DynamoDBAttribute(attributeName = "year_of_release")
    private int releaseYear;

    @DynamoDBAttribute(attributeName = "isbn")
    private String isbn;

    @DynamoDBAttribute(attributeName = "available")
    private String available;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

}
